language: elixir
elixir: '1.8.0'

services:
  - postgresql

env:
  - MIX_ENV: test

install:
  - mix local.hex --force
  - mix deps.get
  - mix local.rebar --force
  - mix ecto.create
  - mix ecto.migrate

script:
  - mix format --check-formatted
  - mix coveralls.travis
